### ISSUE TITLE
*.md declaration files for typescript

### ISSUE THREAD

**Issue by creepinson** [hmsk/vite-plugin-markdown#118]
I had to make a .d.ts file for the *.md files that I have used. So far it looks something like this:

```typescript
import { ReactNode } from "react";

declare module "*.md" {
    export type TableOfContents = {
        level: string;
        content: string;
    }[];

    const res: {
        html?: string;
        ReactComponent: ReactNode;
        attributes: Record<string, never>;
        toc: TableOfContents;
    };
    export default res;
}
```

I can make a PR for this so that markdown files can be imported in tsx components without problems.

**Comment by hmsk** [comment]
Thanks for flagging here!
I prefer to not provide a one size fits all `d.ts` basically, to avoid unintentional forcible declaration and expect each developer declares as they need. However, happy to leave a guide for TS users to declare types efficiently instead.
