### ISSUE TITLE
error: failed to resolve soc

### ISSUE THREAD

**Issue by Daniel-Kao** [hmsk/vite-plugin-markdown#122]
Here it's the thing: I want to use it in vue with toc, but vite failed to resolve toc component and there's no href on h* tags. can't figure out how to solve it, can you provide a guide?

**Comment by hmsk** [comment]
It would be great if you provide a reproducible repo. btw toc isn't "component" but looks like `{ level: string, content: string }[]`

**Comment by hmsk** [comment]
Closing this issue now, but feel free to reopen when you bring more detailed feedback with reproducible repo 😉
