### ISSUE TITLE
display local image file

### ISSUE THREAD

**Issue by tsanyqudsi** [hmsk/vite-plugin-markdown#164]
So far most of the Markdown implementation is using absolute url such as `http://www.url.com/imagefile.jpg`.

I wonder if we can use local file for displaying the image using relative url.

For example :

folder
-- image.png
-- index.md

in `index.md` : 

```
![yay image](./image.png)
```

**Comment by hmsk** [comment]
Thanks for your suggestion. Solving path sounds like build system (in this case, vite)'s duty for me, so I don't think this plugin support specifically so far. Bring your concrete example (it'd be great if it's a repo to run and see easily) if something I can help.
