### ISSUE TITLE
Is anyway or plan to add script to md ？

### ISSUE THREAD

**Issue by xxholly32** [hmsk/vite-plugin-markdown#17]
[content.md](https://github.com/hmsk/vite-plugin-markdown/blob/main/examples/vue/src/assets/content.md)

```
<link-to-repository color="#37ae70">See Repository</link-to-repository>
```
change to 
```
<link-to-repository :color="color">See Repository</link-to-repository>

<script>
export default {
  data() {
    return {
      color: "#37ae70",
    };
  },
};
</script>
```

and add style tag , just like [vuepress](https://v1.vuepress.vuejs.org/guide/getting-started.html)

**Comment by hmsk** [comment]
Since this plugin is focused on importing plain markdown/frontmatter-ed markdown on vite basically, it's not supported currently, nor planned for the future.

VitePress might cover your use-case I guess https://github.com/vuejs/vitepress

**Comment by JasKang** [comment]
@xxholly32  
 like this repo ? https://github.com/JasKang/vite-plugin-vuedoc

**Comment by xxholly32** [comment]
@JasKang yes it`s exactly what i want. job well done

**Comment by hmsk** [comment]
Great project! I'm happy to hear you found what you needed.
