### ISSUE TITLE
[plugin:vite-plugin-markdown] Cannot find module '@babel/preset-react' Require stack:

### ISSUE THREAD

**Issue by KipSong** [hmsk/vite-plugin-markdown#238]
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import mdPlugin, { Mode } from 'vite-plugin-markdown'

defineConfig({
plugins:[
    mdPlugin({
      mode: [Mode.REACT]
    }),
    react(),
]
})

**Comment by kwiat1990** [comment]
@KipSong you need to install the mentioned package as a dev dependency (`npm i -D @babel/preset-react`). After that it works.
