### ISSUE TITLE
Example with react doesn't work

### ISSUE THREAD

**Issue by ymatuhin** [hmsk/vite-plugin-markdown#308]
This doesn't work. But it works ok if I name props that way `<ReactComponent MyComponent={MyComponent} />`.
```tsx
import React from 'react'
import { ReactComponent } from './contents/the-doc.md'
import { MyComponent } from './my-component'

function MyReactApp() {
  return (
    <div>
      <ReactComponent my-component={MyComponent} />
    </div>
}

**Comment by hmsk** [comment]
Thanks for pointing this out. You're right, that should be `MyComponent`
https://github.com/hmsk/vite-plugin-markdown/commit/345dcdf5d38b10d18c1ca72b18c89a8fee112723
