### ISSUE TITLE
Router links

### ISSUE THREAD

**Issue by killjoy1221** [hmsk/vite-plugin-markdown#318]
When creating a link via markdown syntax (`[display](href)`) to a known route in `vue-router` or `react-router`, there should be an option to prefer `<router-link>` (vue) or `<Link>` (react) instead of `<a>`.

It should turn this
```md
[Home](/home)
```
Into this (vue)
```vue
<router-link to="/home">Home</router-link>
```
Or this (react)
```jsx
<Link to="/home">Home</Link>
```

From a quick look at the code, this might not be entirely possible with the current design, but I would be happy to be able to provide my own components to override tags. Right now, passing in a custom component to bridge `<a>` to `<router-link>` via `VueComponentWith({A: MyTag})` doesn't seem to work.

**Comment by hmsk** [comment]
I believe it's on Markdown compilers' area.
`markdown` or `markdownIt` option enables you to intercept compiler's behavior.
