### ISSUE TITLE
Dynamically loading markdown files

### ISSUE THREAD

**Issue by professional-tdi** [hmsk/vite-plugin-markdown#331]
is it possible to use these function as if I were loading it from a variable instead of a specified path?

e.g.
```javascript
// This
export let mdFile;

import { toc, html, attributes } from mdFile;

// Over This
import { toc, html, attributes } from '$lib/markdown/test.md';
```

**Comment by hmsk** [comment]
I think it's impossible (and not the area of this plugin). vite offers "dynamic import" feature, that might be you're looking for: https://vitejs.dev/guide/features.html#dynamic-import
