### ISSUE TITLE
npm ERR! ERESOLVE unable to resolve dependency tree (Svelte 3.44.0)

### ISSUE THREAD

**Issue by arrowtype** [hmsk/vite-plugin-markdown#336]
First: thank you so much for making this library! It seems like it will fill my exact current need. However, I am having trouble installing it...

This issue popped up before (https://github.com/hmsk/vite-plugin-markdown/issues/324) but seems to be a problem again. 

When I try to install, I receive the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: svelte-kit-test@0.0.1
npm ERR! Found: vite@3.1.0-beta.2
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.1.0-beta.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0 || ^3.0.0" from vite-plugin-markdown@2.1.0
npm ERR! node_modules/vite-plugin-markdown
npm ERR!   dev vite-plugin-markdown@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/stephennixon/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephennixon/.npm/_logs/2022-09-03T20_29_59_223Z-debug-0.log
```

Is there a suggested workaround for this?

**Comment by arrowtype** [comment]
It seems that adding the `--force` flag to `npm install` will download things. Getting it to work, however, is a little challenging... so I can’t say for sure whether forcing it is a good or bad idea yet.

**Comment by hmsk** [comment]
SvelteKit is now using vite@3.1.0 so should work
