### ISSUE TITLE
Add plain string mode support

### ISSUE THREAD

**Issue by romelperez** [hmsk/vite-plugin-markdown#364]
## Type

Feature Request

## Feature

What about just having a plain string text to import markdown files in Vite? I would like to process the markdown file in a different way than the HTML mode is providing right now.

-----

Thank you!

**Comment by njzydark** [comment]
> What about just having a plain string text to import markdown files in Vite? I would like to process the markdown file in a different way than the HTML mode is providing right now.

You don't need any plugin, just import and add [`?raw`](https://vitejs.dev/guide/features.html#static-assets) to end:

```js
import javaTemplate from './java.md?raw';
```

**Comment by romelperez** [comment]
@njzydark , oh, didn't know that. Thank you!
