### ISSUE TITLE
ReferenceError: vueRender is not defined

### ISSUE THREAD

**Issue by nailuox** [hmsk/vite-plugin-markdown#444]
Vue: 2.6.x
Vite: 4.x
vite-plugin-markdown: 2.1.0

```js
import { VueComponent } from './pages/00-intro.md'

···

components: {
    MarkdownContent: VueComponent
}

···

<MarkdownContent/>
```

![image](https://github.com/hmsk/vite-plugin-markdown/assets/49058926/949fcd1d-945b-4d83-8be2-21a4c18fe6af)

**Comment by hmsk** [comment]
Unfortunately, Vue 2 is not supported.
