### ISSUE TITLE
there is no type : Mode.RAW 

### ISSUE THREAD

**Issue by NateYip** [hmsk/vite-plugin-markdown#445]
![image](https://github.com/hmsk/vite-plugin-markdown/assets/25640062/ae60ba15-76e5-48a5-95d1-a2be8f5440b4)

version:
vite-plugin-markdown: "^2.1.0",

I would like to load markdown files in a string/raw format. 

i had check the README , but i cant find the solution
What should I do?

**Comment by ReillyBova** [comment]
You could try installing `vite-plugin-markdown@2.2.0-2`, though there appears to be an issue with the table of contents parser
