### ISSUE TITLE
@babel/preset-react should be in package.json dependencies

### ISSUE THREAD

**Issue by noshiro-pf** [hmsk/vite-plugin-markdown#447]
```
 | [vite-plugin-markdown] Cannot find module '@babel/preset-react'
 | Require stack:
 | - /my-repo/node_modules/@babel/core/lib/config/files/plugins.js
 | - /my-repo/node_modules/@babel/core/lib/config/files/index.js
 | - /my-repo/node_modules/@babel/core/lib/index.js
 | - /my-repo/node_modules/@prefresh/vite/src/index.js
 | - /my-repo/node_modules/@preact/preset-vite/dist/cjs/index.js
 | - /my-repo/packages/apps/my-app/config/vite.config.ts
 | - /my-repo/node_modules/vite/dist/node/chunks/dep-a8e37fae.js
 | file: /my-repo/packages/apps/my-app/src/assets/my-file.md

```

**Comment by hmsk** [comment]
Thanks for your feedback! It's an intentional design to avoid installing it unnecessarily for non-React use-cases.

**Comment by noshiro-pf** [comment]
@hmsk Thank you for your reply.


> It's an intentional design to avoid installing it unnecessarily for non-React use-cases.

I see, but I think this should be explained in Setup section of README.md and a working version should be specified in somewhere. Otherwise, this package may someday break with the latest version `@babel/preset-react`.


If you are concerned about unnecessary dependencies being installed for non-React use-cases, I think it's better to separate the npm package and specify it in each package.json.

Can you reopen this issue?

**Comment by hmsk** [comment]
Thanks for giving your opinion.
