### ISSUE TITLE
`compileTemplate` function needs new `id` argument

### ISSUE THREAD

**Issue by etdr** [hmsk/vite-plugin-markdown#47]
Using this package with compiler-sfc 3.0.4 shows the following message:
```
[@vue/compiler-sfc] compileTemplate now requires the `id` option.`.
```
Should be an easy fix, just I thought I'd point it out. The plugin still seems to be working, I thiiink...? Not completely sure.

**Comment by hmsk** [comment]
Thanks for reporting :) will be released as v2.0.0-1
