### ISSUE TITLE
The plugin needs export "default" in Vue mode

### ISSUE THREAD

**Issue by Thief-K** [hmsk/vite-plugin-markdown#62]
- vite: v2.0.0-beta.31
- vue: v3.0.5

When i use this plugin, the console will show `The requested module '/src/markdown.md?import' does not provide an export named 'default'`.

Here is my code:

```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import { plugin as markdown, Mode } from 'vite-plugin-markdown'
import MarkdownIt from 'markdown-it'
import hljs from 'highlight.js'
import taskList from 'markdown-it-task-lists'

const markdownIt: MarkdownIt.Options = new MarkdownIt({
  html: true,
  highlight: function (str: string, lang: string) {
    if (lang && hljs.getLanguage(lang)) {
      return hljs.highlight(lang, str).value
    }
    return ''
  }
}).use(taskList)

export default defineConfig({
  plugins: [vue(), markdown({ mode: [Mode.VUE], markdownIt })]
})
```

If `export default VueComponent;`, and it works.

**Comment by hmsk** [comment]
Could you give the source which is importing `/src/markdown.md` as well? I guess it's just importing without `{ }` 🤔 
I made this plugin to not export `default` intentionally since there is various type of exports.

**Comment by Thief-K** [comment]
You are right, i import `.md` file directly!

So i need to `import { VueComponent as XXX } from './markdown.md'`, if i have lots of markdown files, may be this way could be a little complicated.

**Comment by hmsk** [comment]
Thanks for your feedback!
