### ISSUE TITLE
Feat: Syntax highlighting

### ISSUE THREAD

**Issue by wizardpisces** [hmsk/vite-plugin-markdown#9]
Is there a plan to support syntax highlighting?

**Comment by hmsk** [comment]
I don't think this module support that as default.
We can intervene in compiling Markdown through `markdownIt`, `markdown` option, so you can do syntax highlighting even now.

```js
const markdownItPrism = require('markdown-it-prism'); // https://github.com/jGleitz/markdown-it-prism
const mdPlugin = require('vite-plugin-markdown')

module.exports = {
  plugins: [mdPlugin({
    markdownIt: markdownIt({ html: true }).use(markdownItPrism)
  })]
}
```

Also need to provide CSS by Prism: https://prismjs.com/#basic-usage
