### ISSUE TITLE
how to use img in MD

### ISSUE THREAD

**Issue by shenqistart** [hmsk/vite-plugin-markdown#96]
it is not work when you use  
```
[RUNOOB 图标](http://static.runoob.com/images/runoob-logo.png) 
 <img src="http://static.runoob.com/images/runoob-logo.png" width="50%"> 
```
in MD. the problem is show in blow:

```
16:27:51 [vite] Internal server error: unknown: Unterminated JSX contents (19:14)

  17 | <img src="http://static.runoob.com/images/runoob-logo.png" width="375">
  18 |
> 19 |         </div>
     |               ^
  20 |     
  Plugin: vite-plugin-markdown
```

**Comment by shenqistart** [comment]
i think the npm package need change <img> to <img/>
https://stackoverflow.com/questions/40895179/react-syntax-error-expected-corresponding-jsx-closing-tag-for-img

**Comment by hmsk** [comment]
ah, good point. I will fix it.

**Comment by hmsk** [comment]
Released as https://github.com/hmsk/vite-plugin-markdown/releases/tag/v2.0.2 thanks for your reporting!
